// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

RWTexture2D<float4> SourceMap;

RWTexture2D<float4> ColorMap;

RWTexture2D<float4> PositionMap;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

	ColorMap[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 1.0);

	PositionMap[id.xy] = float4(0.001*id.x, 0.002*id.y, 0.05 + 0.0005*id.x, 1.0);
}
